### ISSUE TITLE
hex file is corrupt

### ISSUE THREAD

**Issue by EtchedPixels** [peterw8102/Z80-Retro#3]
Not sure what you used to generate the second part of your hex file but your checksums appear to be out according to both makerom and gnu binutils.

**Comment by peterw8102** [comment]
The second part is a font. I don't have any problem loading the data using the TL866II programmer, but maybe that doesn't look at the checksums. I'll investigate.

**Comment by peterw8102** [comment]
Error in my font editor (font-edit directory) using the a one's complement of the sum of bytes, not two's complement. I'll fix the bug and rebuild the hex file. Thank you!

**Comment by peterw8102** [comment]
Fixed
